<script>
 class HttpError extends Error {
    constructor(response) {
      super(`${response.status} for ${response.url}`);
      this.name = 'HttpError';
      this.response = response;
    }
  }
  
  function loadJson(url) {
    return fetch(url)
      .then(response => {
        if (response.status == 200) {
          return response.json();
        } else {
          throw new HttpError(response);
        }
      });
  }
  
  // 询问用户名，直到 github 返回一个合法的用户
  async function demoGithubUser() {
    let name = prompt("Enter a name?", "iliakan");
  
    let user 
    while(true){
      try{
        user = await loadJson(`https://api.github.com/users/${name}`)
        break
      }catch(err) {
        if (err instanceof HttpError && err.response.status == 404) {
          alert("No such user, please reenter.");
        } else {
          throw err;
        }
      };

    }

    alert(`Full name: ${user.name}.`);
    return user;
    
  }
  
  demoGithubUser();
</script>
